// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/gRPC/getAgent.proto

package gRPC

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{0}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthReply) Reset()         { *m = HealthReply{} }
func (m *HealthReply) String() string { return proto.CompactTextString(m) }
func (*HealthReply) ProtoMessage()    {}
func (*HealthReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{1}
}

func (m *HealthReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthReply.Unmarshal(m, b)
}
func (m *HealthReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthReply.Marshal(b, m, deterministic)
}
func (m *HealthReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthReply.Merge(m, src)
}
func (m *HealthReply) XXX_Size() int {
	return xxx_messageInfo_HealthReply.Size(m)
}
func (m *HealthReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthReply proto.InternalMessageInfo

func (m *HealthReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// The request message containing the agent's id and project fields.
type AgentRequest struct {
	Companystaffguid     string   `protobuf:"bytes,1,opt,name=companystaffguid,proto3" json:"companystaffguid,omitempty"`
	Attributes           string   `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentRequest) Reset()         { *m = AgentRequest{} }
func (m *AgentRequest) String() string { return proto.CompactTextString(m) }
func (*AgentRequest) ProtoMessage()    {}
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{2}
}

func (m *AgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRequest.Unmarshal(m, b)
}
func (m *AgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRequest.Marshal(b, m, deterministic)
}
func (m *AgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRequest.Merge(m, src)
}
func (m *AgentRequest) XXX_Size() int {
	return xxx_messageInfo_AgentRequest.Size(m)
}
func (m *AgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRequest proto.InternalMessageInfo

func (m *AgentRequest) GetCompanystaffguid() string {
	if m != nil {
		return m.Companystaffguid
	}
	return ""
}

func (m *AgentRequest) GetAttributes() string {
	if m != nil {
		return m.Attributes
	}
	return ""
}

type AgentsRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Attributes           string   `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	SortKey              string   `protobuf:"bytes,5,opt,name=sortKey,proto3" json:"sortKey,omitempty"`
	DescendingOrder      bool     `protobuf:"varint,6,opt,name=descendingOrder,proto3" json:"descendingOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentsRequest) Reset()         { *m = AgentsRequest{} }
func (m *AgentsRequest) String() string { return proto.CompactTextString(m) }
func (*AgentsRequest) ProtoMessage()    {}
func (*AgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{3}
}

func (m *AgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentsRequest.Unmarshal(m, b)
}
func (m *AgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentsRequest.Marshal(b, m, deterministic)
}
func (m *AgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentsRequest.Merge(m, src)
}
func (m *AgentsRequest) XXX_Size() int {
	return xxx_messageInfo_AgentsRequest.Size(m)
}
func (m *AgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentsRequest proto.InternalMessageInfo

func (m *AgentsRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *AgentsRequest) GetAttributes() string {
	if m != nil {
		return m.Attributes
	}
	return ""
}

func (m *AgentsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AgentsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AgentsRequest) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *AgentsRequest) GetDescendingOrder() bool {
	if m != nil {
		return m.DescendingOrder
	}
	return false
}

type AgentsReply struct {
	Agents               []*AgentReply `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AgentsReply) Reset()         { *m = AgentsReply{} }
func (m *AgentsReply) String() string { return proto.CompactTextString(m) }
func (*AgentsReply) ProtoMessage()    {}
func (*AgentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{4}
}

func (m *AgentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentsReply.Unmarshal(m, b)
}
func (m *AgentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentsReply.Marshal(b, m, deterministic)
}
func (m *AgentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentsReply.Merge(m, src)
}
func (m *AgentsReply) XXX_Size() int {
	return xxx_messageInfo_AgentsReply.Size(m)
}
func (m *AgentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_AgentsReply proto.InternalMessageInfo

func (m *AgentsReply) GetAgents() []*AgentReply {
	if m != nil {
		return m.Agents
	}
	return nil
}

// The response message containing the agent data
type AgentReply struct {
	IsActive             bool         `protobuf:"varint,1,opt,name=isActive,proto3" json:"isActive,omitempty"`
	CompanyStaffGuid     string       `protobuf:"bytes,2,opt,name=companyStaffGuid,proto3" json:"companyStaffGuid,omitempty"`
	PersonGuid           string       `protobuf:"bytes,3,opt,name=personGuid,proto3" json:"personGuid,omitempty"`
	MlsDetails           []*MLSDetail `protobuf:"bytes,4,rep,name=mlsDetails,proto3" json:"mlsDetails,omitempty"`
	Roles                []*Role      `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Awards               []*Award     `protobuf:"bytes,6,rep,name=awards,proto3" json:"awards,omitempty"`
	LastUpdateOn         string       `protobuf:"bytes,7,opt,name=lastUpdateOn,proto3" json:"lastUpdateOn,omitempty"`
	LastUpdatedBy        string       `protobuf:"bytes,8,opt,name=lastUpdatedBy,proto3" json:"lastUpdatedBy,omitempty"`
	LicenseNumber        string       `protobuf:"bytes,9,opt,name=licenseNumber,proto3" json:"licenseNumber,omitempty"`
	FirstName            string       `protobuf:"bytes,10,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName           string       `protobuf:"bytes,11,opt,name=middleName,proto3" json:"middleName,omitempty"`
	LastName             string       `protobuf:"bytes,12,opt,name=lastName,proto3" json:"lastName,omitempty"`
	PrimaryPhoneNumber   string       `protobuf:"bytes,13,opt,name=primaryPhoneNumber,proto3" json:"primaryPhoneNumber,omitempty"`
	PrimaryEmailAddress  string       `protobuf:"bytes,14,opt,name=primaryEmailAddress,proto3" json:"primaryEmailAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentReply) Reset()         { *m = AgentReply{} }
func (m *AgentReply) String() string { return proto.CompactTextString(m) }
func (*AgentReply) ProtoMessage()    {}
func (*AgentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{5}
}

func (m *AgentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentReply.Unmarshal(m, b)
}
func (m *AgentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentReply.Marshal(b, m, deterministic)
}
func (m *AgentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentReply.Merge(m, src)
}
func (m *AgentReply) XXX_Size() int {
	return xxx_messageInfo_AgentReply.Size(m)
}
func (m *AgentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentReply.DiscardUnknown(m)
}

var xxx_messageInfo_AgentReply proto.InternalMessageInfo

func (m *AgentReply) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *AgentReply) GetCompanyStaffGuid() string {
	if m != nil {
		return m.CompanyStaffGuid
	}
	return ""
}

func (m *AgentReply) GetPersonGuid() string {
	if m != nil {
		return m.PersonGuid
	}
	return ""
}

func (m *AgentReply) GetMlsDetails() []*MLSDetail {
	if m != nil {
		return m.MlsDetails
	}
	return nil
}

func (m *AgentReply) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AgentReply) GetAwards() []*Award {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *AgentReply) GetLastUpdateOn() string {
	if m != nil {
		return m.LastUpdateOn
	}
	return ""
}

func (m *AgentReply) GetLastUpdatedBy() string {
	if m != nil {
		return m.LastUpdatedBy
	}
	return ""
}

func (m *AgentReply) GetLicenseNumber() string {
	if m != nil {
		return m.LicenseNumber
	}
	return ""
}

func (m *AgentReply) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AgentReply) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *AgentReply) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AgentReply) GetPrimaryPhoneNumber() string {
	if m != nil {
		return m.PrimaryPhoneNumber
	}
	return ""
}

func (m *AgentReply) GetPrimaryEmailAddress() string {
	if m != nil {
		return m.PrimaryEmailAddress
	}
	return ""
}

type MLSDetail struct {
	MlsID                string   `protobuf:"bytes,1,opt,name=mlsID,proto3" json:"mlsID,omitempty"`
	Board                string   `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	IsPrimary            bool     `protobuf:"varint,3,opt,name=isPrimary,proto3" json:"isPrimary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MLSDetail) Reset()         { *m = MLSDetail{} }
func (m *MLSDetail) String() string { return proto.CompactTextString(m) }
func (*MLSDetail) ProtoMessage()    {}
func (*MLSDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{6}
}

func (m *MLSDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MLSDetail.Unmarshal(m, b)
}
func (m *MLSDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MLSDetail.Marshal(b, m, deterministic)
}
func (m *MLSDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MLSDetail.Merge(m, src)
}
func (m *MLSDetail) XXX_Size() int {
	return xxx_messageInfo_MLSDetail.Size(m)
}
func (m *MLSDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_MLSDetail.DiscardUnknown(m)
}

var xxx_messageInfo_MLSDetail proto.InternalMessageInfo

func (m *MLSDetail) GetMlsID() string {
	if m != nil {
		return m.MlsID
	}
	return ""
}

func (m *MLSDetail) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *MLSDetail) GetIsPrimary() bool {
	if m != nil {
		return m.IsPrimary
	}
	return false
}

type Role struct {
	CompanyGuid          string   `protobuf:"bytes,1,opt,name=companyGuid,proto3" json:"companyGuid,omitempty"`
	OfficeGuid           string   `protobuf:"bytes,2,opt,name=officeGuid,proto3" json:"officeGuid,omitempty"`
	RoleCode             string   `protobuf:"bytes,3,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	RoleDescription      string   `protobuf:"bytes,4,opt,name=roleDescription,proto3" json:"roleDescription,omitempty"`
	ActiveSince          string   `protobuf:"bytes,5,opt,name=activeSince,proto3" json:"activeSince,omitempty"`
	IsFulltime           bool     `protobuf:"varint,6,opt,name=isFulltime,proto3" json:"isFulltime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{7}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetCompanyGuid() string {
	if m != nil {
		return m.CompanyGuid
	}
	return ""
}

func (m *Role) GetOfficeGuid() string {
	if m != nil {
		return m.OfficeGuid
	}
	return ""
}

func (m *Role) GetRoleCode() string {
	if m != nil {
		return m.RoleCode
	}
	return ""
}

func (m *Role) GetRoleDescription() string {
	if m != nil {
		return m.RoleDescription
	}
	return ""
}

func (m *Role) GetActiveSince() string {
	if m != nil {
		return m.ActiveSince
	}
	return ""
}

func (m *Role) GetIsFulltime() bool {
	if m != nil {
		return m.IsFulltime
	}
	return false
}

type Award struct {
	AwardTypeCode        string   `protobuf:"bytes,1,opt,name=awardTypeCode,proto3" json:"awardTypeCode,omitempty"`
	AwardTypeDescription string   `protobuf:"bytes,2,opt,name=awardTypeDescription,proto3" json:"awardTypeDescription,omitempty"`
	AwardName            string   `protobuf:"bytes,3,opt,name=awardName,proto3" json:"awardName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Award) Reset()         { *m = Award{} }
func (m *Award) String() string { return proto.CompactTextString(m) }
func (*Award) ProtoMessage()    {}
func (*Award) Descriptor() ([]byte, []int) {
	return fileDescriptor_d12d822959c95d38, []int{8}
}

func (m *Award) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Award.Unmarshal(m, b)
}
func (m *Award) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Award.Marshal(b, m, deterministic)
}
func (m *Award) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Award.Merge(m, src)
}
func (m *Award) XXX_Size() int {
	return xxx_messageInfo_Award.Size(m)
}
func (m *Award) XXX_DiscardUnknown() {
	xxx_messageInfo_Award.DiscardUnknown(m)
}

var xxx_messageInfo_Award proto.InternalMessageInfo

func (m *Award) GetAwardTypeCode() string {
	if m != nil {
		return m.AwardTypeCode
	}
	return ""
}

func (m *Award) GetAwardTypeDescription() string {
	if m != nil {
		return m.AwardTypeDescription
	}
	return ""
}

func (m *Award) GetAwardName() string {
	if m != nil {
		return m.AwardName
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "gRPC.HealthRequest")
	proto.RegisterType((*HealthReply)(nil), "gRPC.HealthReply")
	proto.RegisterType((*AgentRequest)(nil), "gRPC.AgentRequest")
	proto.RegisterType((*AgentsRequest)(nil), "gRPC.AgentsRequest")
	proto.RegisterType((*AgentsReply)(nil), "gRPC.AgentsReply")
	proto.RegisterType((*AgentReply)(nil), "gRPC.AgentReply")
	proto.RegisterType((*MLSDetail)(nil), "gRPC.MLSDetail")
	proto.RegisterType((*Role)(nil), "gRPC.Role")
	proto.RegisterType((*Award)(nil), "gRPC.Award")
}

func init() { proto.RegisterFile("internal/gRPC/getAgent.proto", fileDescriptor_d12d822959c95d38) }

var fileDescriptor_d12d822959c95d38 = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0xe5, 0x36, 0xc9, 0x25, 0x93, 0xf6, 0x5a, 0xf6, 0x4e, 0xa7, 0x55, 0x55, 0xa1, 0xc8,
	0x80, 0x14, 0xf1, 0x90, 0x40, 0x79, 0xe0, 0xb9, 0xd7, 0x42, 0x41, 0xc7, 0xdd, 0x45, 0x2e, 0xf7,
	0x72, 0x6f, 0x1b, 0x7b, 0x92, 0xac, 0x58, 0x7b, 0xcd, 0xee, 0xa6, 0x28, 0x42, 0x08, 0x89, 0xaf,
	0xc0, 0x0b, 0x5f, 0x85, 0x6f, 0x81, 0xc4, 0x57, 0xe0, 0x7b, 0x80, 0x76, 0xbc, 0x8e, 0xed, 0xb6,
	0x12, 0x6f, 0x99, 0xdf, 0xcc, 0x4e, 0x66, 0xff, 0x3b, 0x33, 0x86, 0x73, 0x59, 0x38, 0x34, 0x85,
	0x50, 0xf3, 0x75, 0xb2, 0xb8, 0x9a, 0xaf, 0xd1, 0x5d, 0xae, 0xb1, 0x70, 0xb3, 0xd2, 0x68, 0xa7,
	0x59, 0xcf, 0xc3, 0xb3, 0xf3, 0xb5, 0xd6, 0x6b, 0x85, 0x73, 0x51, 0xca, 0xb9, 0x28, 0x0a, 0xed,
	0x84, 0x93, 0xba, 0xb0, 0x55, 0x4c, 0x7c, 0x02, 0xc7, 0xdf, 0xa0, 0x50, 0x6e, 0x93, 0xe0, 0x8f,
	0x5b, 0xb4, 0x2e, 0xfe, 0x04, 0xc6, 0x35, 0x28, 0xd5, 0x8e, 0xbd, 0x80, 0x81, 0x75, 0xc2, 0x6d,
	0x2d, 0x8f, 0x26, 0xd1, 0x74, 0x94, 0x04, 0x2b, 0x7e, 0x0f, 0x47, 0xf4, 0x57, 0xe1, 0x18, 0xfb,
	0x14, 0x4e, 0x53, 0x9d, 0x97, 0xa2, 0xd8, 0x59, 0x27, 0x56, 0xab, 0xf5, 0x56, 0x66, 0xe1, 0xc4,
	0x03, 0xce, 0x3e, 0x04, 0x10, 0xce, 0x19, 0xb9, 0xdc, 0x3a, 0xb4, 0xfc, 0x80, 0xa2, 0x5a, 0x24,
	0xfe, 0x33, 0x82, 0x63, 0x4a, 0x6e, 0xeb, 0xec, 0xbe, 0x0a, 0x14, 0x26, 0xdd, 0xec, 0xab, 0x20,
	0xeb, 0xff, 0x32, 0xf9, 0x73, 0x7a, 0xb5, 0xb2, 0xe8, 0xf8, 0xe1, 0x24, 0x9a, 0x1e, 0x26, 0xc1,
	0x62, 0xcf, 0xa1, 0xaf, 0x64, 0x2e, 0x1d, 0xef, 0x11, 0xae, 0x0c, 0xc6, 0xe1, 0x89, 0xd5, 0xc6,
	0xbd, 0xc2, 0x1d, 0xef, 0x53, 0xaa, 0xda, 0x64, 0x53, 0x38, 0xc9, 0xd0, 0xa6, 0x58, 0x64, 0xb2,
	0x58, 0xbf, 0x35, 0x19, 0x1a, 0x3e, 0x98, 0x44, 0xd3, 0x61, 0x72, 0x1f, 0xc7, 0x5f, 0xc2, 0xb8,
	0x2e, 0xdd, 0xcb, 0x37, 0x85, 0x81, 0x20, 0x93, 0x47, 0x93, 0xc3, 0xe9, 0xf8, 0xe2, 0x74, 0xe6,
	0xdf, 0x64, 0x16, 0xa4, 0x2b, 0xd5, 0x2e, 0x09, 0xfe, 0xf8, 0x8f, 0x1e, 0x40, 0x83, 0xd9, 0x19,
	0x0c, 0xa5, 0xbd, 0x4c, 0x9d, 0xbc, 0x43, 0xba, 0xf3, 0x30, 0xd9, 0xdb, 0x2d, 0xad, 0x6f, 0xbd,
	0xa6, 0x37, 0x5e, 0xeb, 0x83, 0x8e, 0xd6, 0x7b, 0xee, 0x15, 0x2a, 0xd1, 0x58, 0x5d, 0x50, 0xd4,
	0x61, 0xa5, 0x50, 0x43, 0xd8, 0x1c, 0x20, 0x57, 0xf6, 0x1a, 0x9d, 0x90, 0xca, 0xf2, 0x1e, 0x15,
	0x79, 0x52, 0x15, 0xf9, 0xfa, 0xbb, 0xdb, 0x8a, 0x27, 0xad, 0x10, 0x36, 0x81, 0xbe, 0xd1, 0x0a,
	0x2d, 0xef, 0x53, 0x2c, 0x54, 0xb1, 0x89, 0x56, 0x98, 0x54, 0x0e, 0xf6, 0x11, 0x0c, 0xc4, 0x4f,
	0xc2, 0x64, 0x96, 0x0f, 0x28, 0x64, 0x1c, 0xee, 0xec, 0x59, 0x12, 0x5c, 0x2c, 0x86, 0x23, 0x25,
	0xac, 0x7b, 0x57, 0x66, 0xc2, 0xe1, 0xdb, 0x82, 0x3f, 0xa1, 0xca, 0x3a, 0x8c, 0x7d, 0x0c, 0xc7,
	0x8d, 0x9d, 0xbd, 0xdc, 0xf1, 0x21, 0x05, 0x75, 0x21, 0x45, 0xc9, 0x14, 0x0b, 0x8b, 0x6f, 0xb6,
	0xf9, 0x12, 0x0d, 0x1f, 0x85, 0xa8, 0x36, 0x64, 0xe7, 0x30, 0x5a, 0x49, 0x63, 0xdd, 0x1b, 0x91,
	0x23, 0x07, 0x8a, 0x68, 0x80, 0x57, 0x29, 0x97, 0x59, 0xa6, 0x90, 0xdc, 0xe3, 0x4a, 0xa5, 0x86,
	0xf8, 0xd7, 0xf0, 0x7f, 0x4a, 0xde, 0x23, 0xf2, 0xee, 0x6d, 0x36, 0x03, 0x56, 0x1a, 0x99, 0x0b,
	0xb3, 0x5b, 0x6c, 0x74, 0x51, 0x17, 0x71, 0x4c, 0x51, 0x8f, 0x78, 0xd8, 0x67, 0xf0, 0x2c, 0xd0,
	0xaf, 0x72, 0x21, 0xd5, 0x65, 0x96, 0x19, 0xb4, 0x96, 0x3f, 0xa5, 0x03, 0x8f, 0xb9, 0xe2, 0x77,
	0x30, 0xda, 0xbf, 0x85, 0x6f, 0xdd, 0x5c, 0xd9, 0x6f, 0xaf, 0xc3, 0x24, 0x54, 0x86, 0xa7, 0x4b,
	0x2d, 0x4c, 0xdd, 0x07, 0x95, 0xe1, 0x2f, 0x2d, 0xed, 0xa2, 0xca, 0x48, 0x6f, 0x3f, 0x4c, 0x1a,
	0x10, 0xff, 0x15, 0x41, 0xcf, 0xbf, 0x1b, 0x9b, 0xc0, 0x38, 0xf4, 0xcd, 0x4d, 0x33, 0xb6, 0x6d,
	0xe4, 0xf5, 0xd1, 0xab, 0x95, 0x4c, 0xb1, 0xd5, 0x6b, 0x2d, 0xe2, 0xf5, 0xf1, 0x6f, 0x7f, 0xa5,
	0x33, 0x0c, 0x3d, 0xb6, 0xb7, 0xfd, 0xec, 0xf8, 0xdf, 0xd7, 0x68, 0x53, 0x23, 0x4b, 0xbf, 0x7b,
	0x68, 0xea, 0x46, 0xc9, 0x7d, 0xec, 0xeb, 0x10, 0xd4, 0xe1, 0xb7, 0xb2, 0x48, 0x31, 0xcc, 0x60,
	0x1b, 0xf9, 0x3a, 0xa4, 0xfd, 0x7a, 0xab, 0x94, 0x93, 0x39, 0x86, 0x11, 0x6c, 0x91, 0xf8, 0x57,
	0xe8, 0x53, 0x9b, 0xf9, 0xa6, 0xa0, 0x46, 0xfb, 0x7e, 0x57, 0x56, 0x55, 0x55, 0x97, 0xea, 0x42,
	0x76, 0x01, 0xcf, 0xf7, 0xa0, 0x5d, 0x5f, 0x75, 0xc1, 0x47, 0x7d, 0x5e, 0x53, 0xe2, 0xd4, 0x0b,
	0xd5, 0x5d, 0x1b, 0x70, 0xf1, 0x6f, 0x04, 0x7d, 0x9a, 0x62, 0xf6, 0x1e, 0x86, 0x37, 0x61, 0x1d,
	0x33, 0xd6, 0x99, 0x7a, 0x5a, 0x69, 0x67, 0x0f, 0x36, 0x41, 0x3c, 0xfd, 0xed, 0xef, 0x7f, 0x7e,
	0x3f, 0x88, 0xd9, 0x84, 0x56, 0xf5, 0xdd, 0xe7, 0x73, 0xda, 0x0c, 0xf3, 0x9f, 0xef, 0xef, 0xcf,
	0x5f, 0xd8, 0x2b, 0x18, 0xd5, 0xb9, 0x2d, 0x7b, 0xd6, 0x4a, 0x54, 0x2f, 0xcc, 0xb3, 0x0f, 0xba,
	0xd0, 0xa7, 0x7f, 0x41, 0xe9, 0x4f, 0xd9, 0xd3, 0x4e, 0x7a, 0xcb, 0x5e, 0xd7, 0x0b, 0xff, 0x6a,
	0x83, 0xe9, 0x0f, 0x75, 0xba, 0xce, 0x47, 0xa1, 0x4e, 0xd7, 0xfa, 0x30, 0x3c, 0x4c, 0xb7, 0x21,
	0xe7, 0xcb, 0x83, 0x45, 0xb4, 0x1c, 0xd0, 0xb7, 0xe5, 0x8b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x81, 0xa1, 0x3f, 0x26, 0x9f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	GetAgent(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentReply, error)
	GetAgents(ctx context.Context, in *AgentsRequest, opts ...grpc.CallOption) (*AgentsReply, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) GetAgent(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentReply, error) {
	out := new(AgentReply)
	err := c.cc.Invoke(ctx, "/gRPC.Agent/GetAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetAgents(ctx context.Context, in *AgentsRequest, opts ...grpc.CallOption) (*AgentsReply, error) {
	out := new(AgentsReply)
	err := c.cc.Invoke(ctx, "/gRPC.Agent/GetAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, "/gRPC.Agent/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	GetAgent(context.Context, *AgentRequest) (*AgentReply, error)
	GetAgents(context.Context, *AgentsRequest) (*AgentsReply, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthReply, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC.Agent/GetAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetAgent(ctx, req.(*AgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC.Agent/GetAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetAgents(ctx, req.(*AgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC.Agent/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gRPC.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgent",
			Handler:    _Agent_GetAgent_Handler,
		},
		{
			MethodName: "GetAgents",
			Handler:    _Agent_GetAgents_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Agent_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/gRPC/getAgent.proto",
}
